#ifndef _MAIN_H
#define _MAIN_H
#include "stm32f4xx.h"
#include "led.h"
#include "systick.h"
#include "clock.h"
#include "printf.h"
#include "usart.h"
#include "dma.h"
#include "gps.h"
#include "DataScope_DP.h"
#include "ANO_DT.h"
#include "beep.h"
#include "pwm.h"
#include "timer.h"
#include "mpu6050.h"
#include "iic.h"
#include "nrf24l01.h"
#include "exti.h"
#include "key.h"
#include "motor.h"
#include "hmc5883.h"
#include "adc.h"

#endif
